baseurl = "https://savchenkoyana.github.io/"
title = "Yana's blog"
author = "Yana Savchenko"
canonifyurls = true
paginate = 3
theme = "aether"
themesDir = "themes/" 

[params]
    brand = "Yana's blog"
    dark = "auto"
    highlight = true
    #github = "https://github.com/savchenkoyana"
    #instagram = "https://www.instagram.com/dustanddesky/"

[markup]
  [markup.highlight]
    style = "igor"

[markup.goldmark.renderer]
  # Allow HTML in Markdown
  unsafe = true

  [markup.tableOfContents]
    ordered = true

[taxonomies]
   tag = "tags"
   category = "categories"
